#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=00:50:00


module purge
module load 2022
module load Anaconda3/2022.05

# activate the environment
source activate lambda_equitune

# Arrays of models, datasets, and transformations
# models=('RN50' 'RN101' 'ViT-B/32' 'ViT-B/16')
models=('RN50')
datasets=('ISIC2018')
# transformations=("" "flip" "rot90")
transformations=("")
methods=('vanilla')
# methods=("equitune" "equizero")

# Loop over each model, dataset, and transformation
for method in "${methods[@]}"; do
    for model in "${models[@]}"; do
        for dataset in "${datasets[@]}"; do
            for transformation in "${transformations[@]}"; do
                # Run your code with the current parameters
                srun python EquiCLIP/main_equizero.py --method "${method}" --model "${model}" --dataset_name "${dataset}" --data_transformations "${transformation}" --group_name "${transformation}"
            done
        done
    done
done